
##Obteniendo todos los usuarios
GET http://localhost:8080/users

### Obtener un usuario especifico por id
GET  http://localhost:8080/users/1

### Crear un nuevo usuario 
POST http://localhost:8080/users

Content-Type: application/json

{
  "name": "Juanito ",
  "lastname": "Salinas ",
  "birthDate": "1946-5-17",
  "email": "JuanitoHerrreroe@gmail.com",
  "username": "JuanSalinas",
  "password": "yonomascompro",
  "accountNoExpired": true,
  "accountNoLocked": true,
  "credentialNoExpired": true,
  "roles": [ 
    {
      "id": 2,
      "roleEnum": "CLIENT"
    }
  ],
  "favoriteProducts": [],
  "enabled": true
}

### Probando otras peticiones
//Petición de los productos 
GET http://localhost:8080/products

###
//Petición de las obras 
GET http://localhost:8080/paintings

###
//Petición de las obras 
PUT   http://localhost:8080/paintings/1
Content-Type: application/json

{
    "id": 1,
    "name": "Starry Night",
    "description": "A gorgeous painting by me",
    "creation_date": "2020-09-11",
    "style": "Surrealizmo",
    "price": 2000,
    "favorite": true,
    "category": {
      "id": 2,
      "name": "paintings"
    },
    "image": [
      {
        "id": 2,
        "productName": null,
        "url": "../../assets/Images/imgObras/obra3.jpg"
      }
    ],
    "favoriteOf": [],
    "adittionalFeatures": null,
    "altura_cm": "92",
    "largo_cm": "74",
    "medium": "Oil",
    "support_material": "canvas",
    "available_copies": 3,
    "copies_made": 5,
    "price_copy": 400
  },



### Checar las categorías de productos 

GET http://localhost:8080/products-category



###Agregar a favorito de don Baudelio (id= 5)
POST http://localhost:8080/my-favorites/add
Content-Type: application/json

{
"userId": 5,
"productId": 2
}


### Obtener checar al usuario donde agregamos
GET  http://localhost:8080/users/5

### Probando otras peticiones
//Petición de los productos 
GET http://localhost:8080/products/2


###Eliminar de los favoritos de don baudelio
DELETE http://localhost:8080/my-favorites/remove
Content-Type: application/json

{
"userId": 5,
"productId": 2,
}

### Agregar un producto a favoritos de un usuario desde el controlador del usuario
PUT http://localhost:8080/users/5/favorites/2


###Eliminar la imagen uno de una pintura 
DELETE  http://localhost:8080/paintings/1/1
###
GET http://localhost:8080/images


###
DELETE  http://localhost:8080/images/1
