name: Deploy Frontend

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Debug secrets
        run: |
            echo "HOST: ${{ secrets.VPS_HOST }}"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /ruta/de/proyecto-en-vps

            echo "Pull cambios del repo principal"
            git pull origin main
            
            echo "Build nginx"
            docker compose build nginx
            
            echo "Restart nginx"
            docker compose up -d nginx
